# Generated by Django 3.0.6 on 2020-06-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200603_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shippingprice',
            field=models.IntegerField(default=0),
        ),
    ]
