# Generated by Django 3.0.6 on 2020-06-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_hot_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hot_product',
            new_name='Hair_bundles',
        ),
    ]
