# Generated by Django 3.0.3 on 2020-06-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200613_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='guest',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='device_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
